version: "3.8"

services:
  web:
    build: .
    command: python src/manage.py run -h 0.0.0.0
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
    # Нужно оборачивать в env или передавать с запуском
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=converter
volumes:
  postgres_data: